### PR TITLE
fix: remove prompt highlight on select

### LINKED ISSUE #96: Prompt should be highlighted with purple only on hover and if it's Edit window is opened
Prompt should be highlighted with purple only on hover and if it's Edit window is opened. Remember to highlight the whole folders structure. 
Current behaviour confuses users, as when prompt stays highlighted, users think that it's applied to current opened chat.

### PR DESCRIPTION
**Pull request by denys-kolomiitsev**
Corrected highlight behavior for the prompts.

Issue #96

### CODE REVIEW

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Deployment status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Deployment status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Deployment status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Deployment status: success

**Comment by IlyaBondar** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — APPROVED** [review]

**Pull request merged**
