### PR TITLE
fix: chat header information tooltip performs poorly if system prompt is big

### PR DESCRIPTION
**Pull request by Alexander-Kezik**
- Issue: https://github.com/epam/ai-dial-chat/issues/102

### CODE REVIEW

**Comment by mikitabut** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — APPROVED** [review]

**Comment by IlyaBondar** [comment]
/deploy-review
>Deployment status: success

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: success

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: failed

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: success

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: success

**Pull request merged**
