### PR TITLE
fix(chat-e2e): move vertexai back to tests

### PR DESCRIPTION
**Pull request by roman-romanov-o**
Vertex AI  hanging problem was fixed here:
https://github.com/epam/ai-dial-adapter-vertexai/pull/117

### CODE REVIEW

**Comment by roman-romanov-o** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2061.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by irinakartun — APPROVED** [review]

**Comment by roman-romanov-o** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2061.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by roman-romanov-o** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2061.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by roman-romanov-o** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2061.nightly-test.deltixhub.io
>E2E tests status: failed

**Pull request merged**
