### PR TITLE
feat(chat): implement provider auto-redirect to skip provider selection page

### PR DESCRIPTION
**Pull request by valerydluski**
**Description:**

Auto-redirect to default provider, bypassing the provider selection page for improved user flow.

Issues:

**UI changes**

**Checklist:**

- [x] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [ ] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [x] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

### CODE REVIEW

**Comment by valerydluski** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/518789)

**Comment by valerydluski** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/519074)

**Comment by IlyaBondar** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/521083)

**Comment by IlyaBondar** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/528772)

**Comment by valerydluski** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/539886)

**Comment by IlyaBondar** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/540473)

**Comment by valerydluski** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2116.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by IlyaBondar** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2116.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by nartovm** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2116.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by irinakartun — DISMISSED** [review]

**Comment by IlyaBondar** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2116.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by valerydluski** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2116.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by valerydluski** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2116.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by nartovm — DISMISSED** [review]

**Comment by nartovm** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2116.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by nartovm** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2116.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by valerydluski** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2116.nightly-test.deltixhub.io
>E2E tests status: success

**Review by nartovm — APPROVED** [review]

**Review by IlyaBondar — APPROVED** [review]

**Pull request merged**
