### PR TITLE
feat(chat): add modulify-ui library (Issue #2331)

### PR DESCRIPTION
**Pull request by IlyaBondar**
**Description:**

This MR adds modulify-ui, a React library comprised of two powerful tools, Inversify and ComponentBuilder, designed to enhance component flexibility and simplify complex customization processes.

Inversify: Decouple component implementations for easy swapping and conflict-free customization of forked code.
ComponentBuilder: Structure component building with fine-grained control over state, styles, HTML, and more.

Author: @sergesha

**Issues:**
- Issue #2331 

**Base PR:**

- #2256 

**Checklist:**

- [x] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [x] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [x] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

### CODE REVIEW

**Comment by IlyaBondar** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2328.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by IlyaBondar** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2328.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by sergey-shakhmatov-dbg — APPROVED** [review]

**Comment by IlyaBondar** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2328.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by IlyaBondar** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2328.nightly-test.deltixhub.io
>E2E tests status: success

**Review by Gimir — APPROVED** [review]
Reviewed the documentation and tested several examples. Overall, I like it, but some examples in the docs don't work, specifically calling the render method immediately after bind in a chain

**Pull request merged**
