### PR TITLE
chore: GitHub workflow update

### PR DESCRIPTION
**Pull request by nepalevov**
- adding CODEOWNERS
- disabling blank issues
- replacing PR title checker with analog
- adding security policy description

### CODE REVIEW

**Review by mikitabut — DISMISSED** [review]

**Review by mikitabut — DISMISSED** [review]

**Comment by nepalevov** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-615.nightly-test.deltixhub.io
>E2E tests status: success

**Review by IlyaBondar — DISMISSED** [review]

**Pull request merged**
