### PR TITLE
fix(chat): fix cutting conversation name if named from attachment link (Issue #1313)

### LINKED ISSUE #1313: [Attach link] Chat name is not cut to 160 symbols if the chat is named as link title automatically
### EPAM AI DIAL chat version

0.10.0

### What happened?

*Preparation:*

1. Create chat based on DIAL RAG application
2. In input message field click on Clip -> Attach link 
3. Copy-paste any site address to Address field (example, https://www.epam.com/)
4. Type Title ~200 symbols. For example, 
Lorem ipsum dolor sit amet consectetur adipiscing elit. Donec efficitur ullamcorper mauris vel efficitur enim venenatis in. Phasellus fermentum quam sed lacinia fermentum. Ut vitae ullamcorper odio!!
5. Click on Attach
6. Send the message

*Steps:*
Check chat name in chat header and conversation panel (hover over the chat name in chat header or copy-paste the name in edit mode on conversation panel) -> Conversation name is not cut -> **bug**

image

**Expected result:** chat name should be cut to 160 symbols
Note: Please do the same fix if to name the chat using link only (add link); using attachment name (for example, .png in attachment)

### Confidential information

- [X] I confirm that do not share any confidential information

### PR DESCRIPTION
**Pull request by denys-kolomiitsev**
**Description:**

- Fixed cutting conversation name if named from attachment link. Added additional check.

Issues:

- Issue #1313 

**Checklist:**

- [x] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [x] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [x] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

### CODE REVIEW

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1669.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1669.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1669.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1669.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1669.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1669.nightly-test.deltixhub.io
>E2E tests status: success

**Review by Alexander-Kezik — APPROVED** [review]

**Pull request merged**
