### PR TITLE
feat: add announcement banner (#256)(#266)

### PR DESCRIPTION
**Pull request by mikitabut**

### CODE REVIEW

**Comment by mikitabut** [comment]
/deploy-review
>Deployment status: success

**Comment by mikitabut** [comment]
/deploy-review
>Deployment status: success

**Comment by mikitabut** [comment]
/deploy-review
>Deployment status: success

**Comment by mikitabut** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — APPROVED** [review]

**Pull request merged**
