### PR TITLE
chore: redesign settings panel (Issue #492)

### PR DESCRIPTION
**Pull request by Alexander-Kezik**
- Issue: https://github.com/epam/ai-dial-chat/issues/492

### CODE REVIEW

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: success

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: success

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: success

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — DISMISSED** [review]

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — APPROVED** [review]

**Pull request merged**
