### PR TITLE
e2e: added tests for side panels resizing

### PR DESCRIPTION
**Pull request by irinakartun**

### CODE REVIEW

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Review by Alexander-Kezik — APPROVED** [review]

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Pull request merged**
