### PR TITLE
e2e: added tests for compare feature

### PR DESCRIPTION
**Pull request by irinakartun**
added tests for compare feature;
updated e2e desktop viewport

### CODE REVIEW

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — APPROVED** [review]

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Pull request merged**
