### PR TITLE
fix(chat): scroll down icon position (Issue #1611, #1632, #1660)

### PR DESCRIPTION
**Pull request by Derikyan**
**Description:**

scroll down icon should be at the right bottom corner in the chat
No scroll down button for chat with not allowed model

Issues:

- Issue #1611 
- Issue #1632 
- Issue #1660 

**UI changes**

Before:
Снимок экрана 2024-06-25 в 09 36 50
Снимок экрана 2024-06-25 в 09 41 49
Снимок экрана 2024-06-25 в 09 42 02

After:
Снимок экрана 2024-06-25 в 09 43 38
Снимок экрана 2024-06-25 в 09 45 41
Снимок экрана 2024-06-25 в 09 45 50
Снимок экрана 2024-06-28 в 17 30 48

**Checklist:**

- [x] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [x] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [x] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

### CODE REVIEW

**Comment by Derikyan** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1654.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by Derikyan** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1654.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by Derikyan** [comment]
/deploy-review

>Environment URL: https://chat-ai-dial-chat-pr-1654.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by Derikyan** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1654.nightly-test.deltixhub.io
>E2E tests status: success

**Review by denys-kolomiitsev — DISMISSED** [review]

**Comment by Derikyan** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1654.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by Derikyan** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1654.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by Derikyan** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1654.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by Derikyan** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1654.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by denys-kolomiitsev** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1654.nightly-test.deltixhub.io
>E2E tests status: success

**Review by denys-kolomiitsev — APPROVED** [review]

**Pull request merged**
