### PR TITLE
feature: added e2e tests for playback feature

### PR DESCRIPTION
**Pull request by irinakartun**
added e2e tests for playback feature

### CODE REVIEW

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Review by denys-kolomiitsev — APPROVED** [review]

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by alexey-ban** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Pull request merged**
