### PR TITLE
e2e: added couple of tests for import-export

### PR DESCRIPTION
**Pull request by irinakartun**
added first tests

### CODE REVIEW

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Review by denys-kolomiitsev — APPROVED** [review]

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Pull request merged**
