### PR TITLE
e2e: long names truncate and sidebar search tests

### PR DESCRIPTION
**Pull request by irinakartun**
Added tests to verify long names truncation; search entities on sidebar panels

### CODE REVIEW

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Review by denys-kolomiitsev — DISMISSED** [review]

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Review by denys-kolomiitsev — APPROVED** [review]

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Pull request merged**
