### PR TITLE
e2e: added tests for prompts shared icons

### PR DESCRIPTION
**Pull request by irinakartun**
tests for prompts shared icons

### CODE REVIEW

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Review by denys-kolomiitsev — DISMISSED** [review]

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Review by denys-kolomiitsev — APPROVED** [review]

**Pull request merged**
