### PR TITLE
fix: fix appling hot keys on playback, but not on a request api key or report issue modals (Issue #515)

### PR DESCRIPTION
**Pull request by Alexander-Kezik**
- Issue: https://github.com/epam/ai-dial-chat/issues/515
- Issue: https://github.com/epam/ai-dial-chat/issues/480

### CODE REVIEW

**Comment by Alexander-Kezik** [comment]
/deploy-review
>Deployment status: success

**Comment by IlyaBondar** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — COMMENTED** [review]
Need to set `initialFocus` for both dialogs
image
image
and not allow open both dialogs together
image

**Comment by IlyaBondar** [comment]
/deploy-review
>Deployment status: success

**Comment by IlyaBondar** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — APPROVED** [review]

**Pull request merged**
