### PR TITLE
feat(chat-e2e): enabled import-export e2e tests

### PR DESCRIPTION
**Pull request by irinakartun**

### CODE REVIEW

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-789.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by mikitabut — DISMISSED** [review]

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-789.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-789.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-789.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-789.nightly-test.deltixhub.io
>E2E tests status: success

**Review by mikitabut — APPROVED** [review]

**Pull request merged**
