### PR TITLE
feat(chat): remove empty chat settings (Issue #1656)

### PR DESCRIPTION
**Pull request by mikitabut**
**Description:**

We should highlight new conversation button on mobile
We need to get rid of empty chat settings and show them just icon of model, name of model and short description of model in this conversation

Issues:

- Issue #1656 

**UI changes**

[Design](https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=9566-4310&t=aTrE4lDkQYt5eohI-1)
image

**Checklist:**

- [x] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [x] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [x] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

### CODE REVIEW

**Comment by mikitabut** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by denys-kolomiitsev — DISMISSED** [review]

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status:

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by IlyaBondar — COMMENTED** [review]
@mikitabut ,
I suppose we don't need tooltip here
image
image

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status: success

**Review by IlyaBondar — CHANGES_REQUESTED** [review]
need to implement switching between these two views

**Comment by dspashynskyi** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-1657.nightly-test.deltixhub.io
>E2E tests status: failed

**Pull request closed without merging**
