### PR TITLE
feat(chat): add empty phase for playback controls (Issue #600)

### PR DESCRIPTION
**Pull request by mikitabut**
Issue #600

### CODE REVIEW

**Comment by mikitabut** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-644.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by mikitabut** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-644.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by mikitabut** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-644.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by mikitabut** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-644.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by mikitabut** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-644.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by irinakartun** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-644.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by mikitabut** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-644.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by mikitabut** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-644.nightly-test.deltixhub.io
>E2E tests status: success

**Review by denys-kolomiitsev — APPROVED** [review]

**Pull request merged**
