### PR TITLE
e2e: add tests for replay feature

### PR DESCRIPTION
**Pull request by irinakartun**
add e2e tests for replay feature

### CODE REVIEW

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: failed

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Comment by irinakartun** [comment]
/deploy-review
>Deployment status: success

**Review by IlyaBondar — APPROVED** [review]

**Pull request merged**
